// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eajgrltqkfpjkluhcfvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhamdybHRxa2ZwamtsdWhjZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzE1NzMsImV4cCI6MjA1NzgwNzU3M30.CF9svC7cQZI-w65XgXWUKMms2EDR89ORreiJqzuH8SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);